# Generated by Django 5.1.1 on 2025-09-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crop_price',
            fields=[
                ('s_no', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=40)),
                ('commodity', models.CharField(max_length=40)),
                ('min_Price', models.BigIntegerField()),
                ('max_Price', models.BigIntegerField()),
                ('modal_Price', models.BigIntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
