# Generated by Django 5.1.1 on 2025-09-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_price', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop_price',
            name='Grade',
            field=models.CharField(default='Local', max_length=15),
        ),
        migrations.AddField(
            model_name='crop_price',
            name='market_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='crop_price',
            name='state',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='crop_price',
            name='variety',
            field=models.CharField(default='Other', max_length=40),
        ),
        migrations.AlterField(
            model_name='crop_price',
            name='city',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='crop_price',
            name='commodity',
            field=models.CharField(default='', max_length=40),
        ),
    ]
