# Generated by Django 5.1.1 on 2025-09-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_price', '0002_crop_price_grade_crop_price_market_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_price',
            name='max_Price',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='crop_price',
            name='min_Price',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='crop_price',
            name='modal_Price',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
