# Generated by Django 5.1.1 on 2025-09-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_price', '0003_alter_crop_price_max_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_price',
            name='s_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
